/*
    DEFENSIVE PROGRAMMING :
        PROGRAMMIN UNDER THE ASSUMPTION THAT ALL THE ARGUMENTS TO BE RECEIVED WILL BE OF THE WRONG TYPE, WRONG VALUE OR BOTH

        THIS MANNAER OF CODING WILL PREVENT ERRORS AS YOU WILL BE CODING WITH THIS MANNER OF THINKING
        "ALL THINGS THAT CAN GO WRONG WILL GO WRONG"

*/
