/*
    BENEFITS OF OOP
        1. MAKES CODE MORE FLEXIBLE
        2. ALLOWS MODULAR CODE
        3. MAKES CODE REUSABLE

    PRINCIPLES OF OOP
        1. INHERITANCE
        2. ENCAPSULATION
        3. ABSTRACTION
        4. POLYMORPHISM

*/

